<link href="/css/common.css" rel="stylesheet"/>
<title>Site Map - Bill Coderepo</title>
<div class="panel panel-warning">
    <!-- panel heading -->
    <div class="panel-heading">
        <h2>Site Map</h2>
    </div>
    <!-- panel body -->
    <div class="panel-body">
        <canvas id="sitemap"></canvas>
    </div>
    <!-- panel footer -->
    <!--<div class="panel-footer">
    </div>-->
</div>

<!-- ------------------------------------------javascript--------------------------------------------------- -->
<script src="/assets/arborJs/arbor.js"></script>
<script src="/assets/arborJs/arbor-tween.js"></script>
<script src="/assets/arborJs/arbor-graphics.js"></script>
<script src="/js/default/site-map.js"></script>