<link href="/assets/datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen"/>
<link href="/css/common.css" rel="stylesheet"/>
<div class="panel panel-warning">
    <!-- panel heading -->
    <div class="panel-heading">
        <h2>Grain Recycle History chart</h2>
    </div>
    <!-- panel body -->
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-12 col-md-10 col-lg-12">
                <span class="bill_font_bold_green">All Grain Recycle History data by day</span>
                <hr>
                <form action="#" method="get" id="formSearch" class="form-inline">
                    Start Date: <input type="text" class="form-control form_date bill-ime-disabled"
                                       id="day_start_date" name="day_start_date"/>
                    End Date: <input type="text" class="form-control form_date bill-ime-disabled"
                                     id="day_end_date" name="day_end_date"/>
                    <button class="btn btn-primary" type="submit" id="btn_search_day">
                        <span class="glyphicon glyphicon-search"></span>
                        <span>Search</span>
                    </button>
                    &nbsp;&nbsp;&nbsp;&nbsp;
                </form>
            </div>
            <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="bill-chart-canvas_all">
                    <canvas id="grain_recycle_history_line_chart_all"></canvas>
                </div>
            </div>

            <div class="col-sm-12 col-md-10 col-lg-12">
                <span class="bill-margin-left bill_font_bold_green">All Grain Recycle History data by month</span>
                <hr>
                <form action="#" method="get" id="formSearchMonth" class="form-inline">
                    Start Date: <input type="text" class="form-control form_date bill-ime-disabled"
                                       id="month_start_date" name="month_start_date"/>
                    End Date: <input type="text" class="form-control form_date bill-ime-disabled"
                                     id="month_end_date" name="month_end_date"/>
                    <button class="btn btn-primary" type="submit" id="btn_search_month">
                        <span class="glyphicon glyphicon-search"></span>
                        <span>Search</span>
                    </button>
                    &nbsp;&nbsp;&nbsp;&nbsp;
                </form>
            </div>

            <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="bill-chart-canvas">
                    <canvas id="grain_recycle_history_line_chart"></canvas>
                </div>
                <div class="bill-chart-canvas bill-margin-left">
                    <canvas id="grain_recycle_history_bar_chart"></canvas>
                </div>
            </div>
        </div>
    </div>
    <!-- panel footer -->
    <!--<div class="panel-footer">
    </div>-->
</div>

<!-- ------------------------------------------javascript--------------------------------------------------- -->
<script src="/assets/chart.js/Chart.min.js"></script>
<script src="/assets/datetimepicker/js/bootstrap-datetimepicker.js" charset="UTF-8"></script>
<script src="/assets/datetimepicker/js/locales/bootstrap-datetimepicker.zh-CN.js" charset="UTF-8"></script>
<script src="/js/public/datetimepicker.js"></script>
<script src="/assets/jquery-serialize-object/js/jquery.serialize-object.min.js"></script>
<script src="/js/public/util.js"></script>
<script src="/js/person/grain-recycle-history-chart.js"></script>
<script src="/js/public/chart.js"></script>