<link href="/css/common.css" rel="stylesheet"/>
<div class="panel panel-warning">
    <!-- panel heading -->
    <div class="panel-heading">
        <h2>Bad history chart</h2>
    </div>
    <!-- panel body -->
    <div class="panel-body">
        <div class="row">
            <form class="form-inline">
            </form>
        </div>
        <hr>

        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <span class="bill_font_bold_green">All bad history data by day</span>

                <div class="bill-chart-canvas_all">
                    <canvas id="bad_history_line_chart_all"></canvas>
                </div>
            </div>
        </div>
    </div>
    <!-- panel footer -->
    <!--<div class="panel-footer">
    </div>-->
</div>

<!-- ------------------------------------------javascript--------------------------------------------------- -->
<script src="/assets/chart.js/Chart.min.js"></script>
<script src="/js/public/util.js"></script>
<script src="/js/bad-history-chart.js"></script>
<script src="/js/public/chart.js"></script>