<link href="/assets/datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen"/>
<link href="/css/common.css" rel="stylesheet"/>
<title>Toutiao Article - Bill Coderepo</title>
<div class="panel panel-warning">
    <!-- panel heading -->
    <div class="panel-heading">
        <h2>Toutiao Article</h2>
    </div>
    <!-- panel body -->
    <div class="panel-body">
        <div class="row">
            <form action="#" method="get" id="formSearch" class="form-inline">
                <div class="col-sm-10 col-md-10 col-lg-10">
                    日期: <input type="text" class="form-control form_date bill-ime-disabled"
                               id="date" name="date"/>
                    文章关键字: <input type="text" class="form-control" id="keyword" name="keyword"/>
                    <button class="btn btn-primary" type="submit" id="btn_search">
                        <span class="glyphicon glyphicon-search"></span>
                        <span>搜索</span>
                    </button>
                    &nbsp;&nbsp;&nbsp;&nbsp;
                </div>
                <div class="col-sm-2 col-md-2 col-lg-2 text-right">
                    <select name="page_length" id="page_length" class="form-control">
                        <option value="25">25</option>
                        <option value="50">50</option>
                        <option value="75">75</option>
                        <option value="100">100</option>
                    </select>
                    &nbsp;<label>每页</label>
                </div>
                <input type="hidden" id="current_page" name="current_page"/>
            </form>
        </div>
        <hr>
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <table id="tbl" class="table table-striped table-bordered bill_table text-center">
                    <thead>
                    <tr>
                        <td>序号</td>
                        <td class="bill_table_td_50">文章</td>
                        <td>日期</td>
                        <td>操作</td>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- panel footer -->
    <div class="panel-footer">
        <div class="row">
            <div id="div_pagination" class="col-sm-12 col-md-12 col-lg-12 text-right">
            </div>
        </div>
    </div>
</div>
<!-- modal -->
<div id="modalToutiaoArticle" class="modal fade">
    <div class="modal-dialog bill_modal_md">
        <div class="modal-content">
            <div class="modal-header">
                <span>修改</span>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <form id="formToutiaoArticle" action="#" method="post" enctype="multipart/form-data" class="form-inline">
                <div class="modal-body">
                    <div class="input-group">
                        <span class="input-group-addon">date：</span>
                        <input type="text" name="toutiao_article_date" id="toutiao_article_date" class="form-control"/>
                    </div>
                    <br />
                    <div class="input-group">
                        <span class="input-group-addon">title：</span>
                        <input type="text" name="toutiao_article_title" id="toutiao_article_title" class="form-control"/>
                    </div>
                    <br />
                    <div class="input-group">
                        <span class="input-group-addon">url：</span>
                        <input type="text" name="toutiao_article_url" id="toutiao_article_url" class="form-control"/>
                    </div>
                    <br />
                        <input type="hidden" id="toutiao_article_ttid" name="toutiao_article_ttid"/>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success" id="btn_submit_toutiao_article">提交</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">关闭</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- ------------------------------------------javascript--------------------------------------------------- -->
<script src="/assets/pagination/jquery.twbsPagination.min.js"></script>
<script src="/assets/datetimepicker/js/bootstrap-datetimepicker.js" charset="UTF-8"></script>
<script src="/assets/datetimepicker/js/locales/bootstrap-datetimepicker.zh-CN.js" charset="UTF-8"></script>
<script src="/js/public/datetimepicker.js"></script>
<script src="/assets/jquery-serialize-object/js/jquery.serialize-object.min.js"></script>
<script src="/js/public/jAjaxWidget.js"></script>
<script src="/js/public/jCommon.js"></script>
<script src="/js/public/alertMessage.js"></script>
<script src="/js/public/pagination.js"></script>
<script src="/js/person/toutiao-article.js"></script>