<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <link href="/css/common.css" rel="stylesheet" />
    </head>
    <body>
        <div class="panel panel-warning">
            <!-- panel heading -->
            <div class="panel-heading">
                <h2>Finance Category</h2>
            </div>
            <!-- panel body -->
            <div class="panel-body">
                <div class="row">
                    <form class="form-inline">
                        <div class="col-sm-10 col-md-10 col-lg-10">
                            分类名: <input type="text" class="form-control" id="keyword"/>
                            <button class="btn btn-primary" type="button" id="btn_search">
                                <span class="glyphicon glyphicon-search"></span>
                                <span>搜索</span>
                            </button>&nbsp;&nbsp;&nbsp;&nbsp;
                            <button class="btn btn-success" type="button" id="btn_add">
                                <span class="glyphicon glyphicon-plus"></span>
                                <span>新增</span>
                            </button>&nbsp;&nbsp;&nbsp;&nbsp;
                        </div>
                        <div class="col-sm-2 col-md-2 col-lg-2 text-right">
                            <select name="page_length" id="page_length" class="form-control">
                                <option value="25">25</option>
                                <option value="50">50</option>
                                <option value="75">75</option>
                                <option value="100">100</option>
                            </select>
                            &nbsp;<label>每页</label>
                        </div>
                    </form>
                </div><hr>

                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12">
                        <table class="table table-striped table-bordered bill_table text-center">
                            <tr>
                                <td>序号</td>
                                <td>分类名</td>
                                <td>父级分类名</td>
                                <td>权重</td>
                                <td>更新时间</td>
                                <td>操作</td>
                            </tr>
                            <tbody>
                            <?php for($i = 0, $len = count($this->data); $i < $len; $i++){ ?>
                                <tr>
                                    <td><?php echo ($this->start + $i + 1); ?></td>
                                    <td><?php echo $this->data[$i]['fc_name']; ?></td>
                                    <td><?php echo $this->data[$i]['fc_parent_id'] == 0 ? '无' : $this->parents[$this->data[$i]['fc_parent_id']]; ?></td>
                                    <td><?php echo $this->data[$i]['fc_weight']; ?></td>
                                    <td><?php echo $this->data[$i]['fc_update_time']; ?></td>
                                    <td>
                                        <a href="#" id="<?php echo 'modify_' . $this->data[$i]['fc_id']; ?>">修改</a>
                                        <a href="#" id="<?php echo 'delete_' . $this->data[$i]['fc_id']; ?>">删除</a>
                                    </td>
                                </tr>
                            <?php } ?>

                            <?php if (count($this->data) == 0) { ?>
                                <tr>
                                    <td colspan="5" class="bill_table_no_data">对不起,没有符合条件的数据</td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- panel footer -->
            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-6 col-md-6 col-lg-6 text-left">
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-6 text-right">
                        <ul id="pagination" class="pagination-md"></ul>
                    </div>
                </div>
            </div>
        </div>

        <!-- modal -->
        <div id="addFinancecategoryModal" class="modal fade">
            <div class="modal-dialog bill_modal_sm" >
                <div class="modal-content">
                    <div class="modal-header">
                        <span>新增</span>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>

                    <form id="addFinancecategoryForm" action="#" method="post" enctype="multipart/form-data" class="form-inline">
                        <div class="modal-body">
                            <div class="input-group">
                                <span class="input-group-addon">分类名称：</span>
                                <input type="text" name="add_financecategory_name" id="add_financecategory_name" class="form-control"/>
                            </div><br />
                            <div class="input-group">
                                <span class="input-group-addon">父级分类：</span>
                                <select name="add_financecategory_parent_id" id="add_financecategory_parent_id" class="form-control">
                                    <option value="0">无</option>
                                    <?php foreach ($this->parents as $key => $value){ ?>
                                        <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
                                    <?php } ?>
                                </select>
                            </div><br />
                            <div class="input-group">
                                <span class="input-group-addon">权重：</span>
                                <input type="text" name="add_financecategory_weight" id="add_financecategory_weight" class="form-control" value="0"/>
                            </div><br />
                        </div>

                        <div class="modal-footer">
                            <button type="submit" class="btn btn-success" id="btn_submit_add">提交</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">关闭</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div id="modifyFinancecategoryModal" class="modal fade" >
            <div class="modal-dialog bill_modal_sm" >
                <div class="modal-content">
                    <div class="modal-header">
                        <span>修改</span>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <form id="modifyFinancecategoryForm" action="#" method="post" enctype="multipart/form-data" class="form-inline">
                        <div class="modal-body" >
                            <div class="input-group">
                                <span class="input-group-addon">名称：</span>
                                <input type="text" name="modify_financecategory_name" id="modify_financecategory_name" class="form-control"/>
                            </div><br />
                            <div class="input-group">
                                <span class="input-group-addon">父级分类：</span>
                                <select name="modify_financecategory_parent_id" id="modify_financecategory_parent_id" class="form-control">
                                    <option value="0">无</option>
                                    <?php foreach ($this->parents as $key => $value){ ?>
                                        <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
                                    <?php } ?>
                                </select>
                            </div><br />
                            <div class="input-group">
                                <span class="input-group-addon">权重：</span>
                                <input type="text" name="modify_financecategory_weight" id="modify_financecategory_weight" class="form-control"/>
                            </div><br />
                            <input type="hidden" id="modify_financecategory_fc_id" name="modify_financecategory_fc_id"/>
                        </div>

                        <div class="modal-footer">
                            <button type="submit" class="btn btn-success" id="btn_submit_modify">提交</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">关闭</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- ------------------------------------------javascript--------------------------------------------------- -->
        <script type="text/javascript" src="http://cdn.bootcss.com/jquery/1.11.0/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="/bootstrap/js/jquery-1.11.0.min.js"><\/script>')</script>
        <script src="/pagination/jquery.twbsPagination.min.js"></script>
        <script src="/js/util.js"></script>
        <script src="/js/common.js"></script>
        <script src="/js/alertInfo.js"></script>
        <script>
        $(document).ready(function(){
            $('#keyword').val('<?php echo $this->keyword; ?>');
            $('#page_length').val(<?php echo $this->page_length; ?>);
        });

        $('#keyword').on('keydown', function(event){
            if (event.keyCode == 13) {
                //enter key
                event.preventDefault();
                $('#btn_search').click();
            }
        });

        $('#btn_search').on('click', function(){
            var keyword = $.trim($('#keyword').val());
            var current_page = <?php echo $this->current_page; ?>;
            var page_length = <?php echo $this->page_length; ?>;
            search(current_page, page_length, keyword);
        });

        $('#btn_add').on('click', function(){
            window.addFinancecategoryForm.reset();
            $('#btn_submit_add').attr('disabled', false);
            $('#addFinancecategoryModal').modal('show');
        });

        $('#addFinancecategoryForm').on('submit', (function(event){
            event.preventDefault();

            var error_num = validInput('add');
            if(error_num == 0) {
                $('#btn_submit_add').attr('disabled', true);
                $('#btn_add_financecategory').attr('disabled', true);
                var post_url = '/person/financecategory/addfinancecategory';
                var post_data = new FormData(this);
                var msg_success = MESSAGE_ADD_SUCCESS;
                var msg_error = MESSAGE_ADD_ERROR;
                var method = 'post';
                callAjaxWithForm(post_url, post_data, msg_success, msg_error, method);
            }
        }));

        $('a[id^=modify_]').on('click', function(){
            var fc_id = $(this).attr('id').substr('modify_'.length);
            var post_url = '/person/financecategory/getfinancecategory';
            var post_data = {
                'fc_id' : fc_id
            };
            var method = 'get';
            var success_function = function(result){
                $('#modify_financecategory_name').val(result.fc_name);
                $('#modify_financecategory_parent_id').val(result.fc_parent_id);
                $('#modify_financecategory_weight').val(result.fc_weight);
                $('#modify_financecategory_fc_id').val(result.fc_id);
                $('#btn_submit_modify').attr('disabled', false);
                $('#modifyFinancecategoryModal').modal('show');
            };
            callAjaxWithFunction(post_url, post_data, success_function, method);
        });

        $('#modifyFinancecategoryForm').on('submit', (function(event){
            event.preventDefault();

            var error_num = validInput('modify');
            if(error_num == 0) {
                $('#btn_submit_modify').attr('disabled', true);
                var post_url = '/person/financecategory/modifyfinancecategory';
                var post_data = new FormData(this);
                var msg_success = MESSAGE_MODIFY_SUCCESS;
                var msg_error = MESSAGE_MODIFY_ERROR;
                var method = 'post';
                callAjaxWithForm(post_url, post_data, msg_success, msg_error, method);
            }
        }));

        $('a[id^=delete_]').on('click', function(){
            if (confirm(MESSAGE_DELETE_CONFIRM)) {
                var fc_id = $(this).attr('id').substr('delete_'.length);
                var url = '/person/financecategory/deletefinancecategory';
                var data = {
                    'fc_id' : fc_id
                };
                var msg_success = MESSAGE_DELETE_SUCCESS;
                var msg_error = MESSAGE_DELETE_ERROR;
                var method = 'post';
                callAjaxWithAlert(url, data, msg_success, msg_error, method);
            }
        });

        function validInput(type)
        {
            var error_num = 0;
            var name = $.trim($('#' + type + '_financecategory_name').val());
            var weight = $.trim($('#' + type + '_financecategory_weight').val());
            if(name == '') {
                error_num = error_num + 1;
                alert(MESSAGE_NAME_ERROR);
            } else if (!isUnsignedInt(weight)) {
                error_num = error_num + 1;
                alert(MESSAGE_WEIGHT_FORMAT_ERROR);
            }

            return error_num;
        }

        /*  --------------------------------------------------------------------------------------------------------  */
        function search(current_page, page_length, keyword)
        {
            var params = {
                'keyword': keyword || $.trim($('#keyword').val()),
                'current_page': current_page || <?php echo $this->current_page; ?>,
                'page_length': page_length || <?php echo $this->page_length; ?>
            };
            location.href = '/person/financecategory/index?' + $.param(params);
        }

        $('#pagination').twbsPagination({
            totalPages: <?php echo $this->total_pages; ?>,
            startPage: <?php echo $this->current_page; ?>,
            visiblePages: 7,
            first: '首页',
            prev: '上一页',
            next: '下一页',
            last: '尾页',
            onPageClick: function (event, page) {
                search(page);
            }
        });

        $('#page_length').on('change', function(){
            search(1, this.value);
        });
        </script>
    </body>
</html>