<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link href="/css/common.css" rel="stylesheet"/>
    </head>
    <body>
        <h2>variety</h2>
        <div class="form-inline">
            Baidu Music download link:&nbsp;&nbsp;
            <input type="text" id="baidu_music_url" class="form-control" style="width: 500px;"
                   placeholder="like:http://music.baidu.com/song/1262598/download?title=&pst=naga&fr="/>&nbsp;&nbsp;
            <button class="btn" type="button" id="btn_generate_download_link">Generate real download link</button><br><br>
            Real download link:(right click and save as.../other will failed!)&nbsp;&nbsp;
            <a href="#" id="generated_baidu_music_url"></a><br><br>
            
            Generate url with underline:&nbsp;&nbsp;
            <input type="text" id="url" class="form-control" style="width: 800px;"/>&nbsp;&nbsp;
            <button class="btn" type="button" id="btn_generate_url">Generate</button>
        </div>
        <a href="#" id="generated_url" target="_blank"></a>

        <br/>
        <a href='#exampleModal' data-toggle="modal">Bootstrap Modal Example</a>

        <!-- Bootstrap Modal -->
        <div id="exampleModal" class="modal fade" >
            <div class="modal-dialog" style="width:300px;height:300px;margin-top:300px;">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>

                    <div class="modal-body">
                        Example: <input type="text"/>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

        <!-- js file & code -->
        <script src="/bootstrap/js/jquery-1.11.0.min.js"></script>
        <script type="text/javascript">
        $('#baidu_music_url').on('keydown', function(event){
            if (event.keyCode == 13) {
                $('#btn_generate_download_link').click();
            }
        });

        $('#btn_generate_download_link').on('click', function(){
            var music_url = $.trim($('#baidu_music_url').val());
            if(music_url != '') {
                $.ajax({
                    url: '/index/downloadbaidumusic',
                    type: 'get',
                    data: {
                        'downlink' : music_url
                    },
                    dataType: 'json',
                    success: function(music_result){
                        //console.log(music_result);
                        if(music_result == '') {
                            alert('generate download link failed!');
                        } else {
                            $('#generated_baidu_music_url').attr('href', music_result).text(music_result);
                        }
                    },

                    error: function(XMLHttpRequest, textStatus, errorThrown) {
                        console.log("XMLHttpRequest.status="+XMLHttpRequest.status+
                            "\nXMLHttpRequest.readyState="+XMLHttpRequest.readyState+
                            "\ntextStatus="+textStatus);
                    }
                });
            } else {
                alert('music url is empty!');
            }
        });

        $('#url').on('keydown', function(event){
            if (event.keyCode == 13) {
                $('#btn_generate_url').click();
            }
        });

        $('#btn_generate_url').on('click', function(){
            var url = $('#url').val();
            if(url != '') {
                url = (url.indexOf('http://') == 0 || url.indexOf('https://') == 0) ? url : ('http://' + url);
                $('#generated_url').attr('href', url).text(url);
            } else {
                alert('url is empty!');
            }
        });
        </script>
    </body>
</html>