<link href="/css/common.css" rel="stylesheet"/>
<title>Variety - Bill Coderepo</title>
<div class="panel panel-warning">
    <!-- panel heading -->
    <div class="panel-heading">
        <h2>Variety</h2>
    </div>
    <!-- panel body -->
    <div class="panel-body">
        <div class="row">
            <form class="form-inline">
                <div class="col-sm-12 col-md-12 col-lg-12">
                    Baidu Music download link:&nbsp;&nbsp;
                    <input type="text" id="baidu_music_url" class="form-control" style="width: 500px;"
                           placeholder="like:http://music.baidu.com/song/1262598/download?title=&pst=naga&fr="/>&nbsp;&nbsp;
                    <button class="btn btn-success" type="button" id="btn_generate_download_link">
                        Generate real download link
                    </button>
                    <br><br>
                    Real download link:(right click and save as.../other will failed!)&nbsp;&nbsp;
                    <a href="#" id="generated_baidu_music_url"></a>
                    <hr>
                    Generate url with underline:&nbsp;&nbsp;
                    <input type="text" id="url" class="form-control" style="width: 800px;"/>&nbsp;&nbsp;
                    <button class="btn btn-success" type="button" id="btn_generate_url">Generate</button>
                    <br/>
                    <a href="#" id="generated_url" target="_blank"></a>
                    <hr>
                    <a href='#exampleModal' data-toggle="modal">Bootstrap Modal Example</a>
                </div>
            </form>
        </div>
        <div class="row col-sm-12 col-md-12 col-lg-12">
            <form class="form-inline">
                <div class="btn-group" role="group">
                    <button type="button" class="btn btn-default dropdown-toggle" title="Select columns to export" data-toggle="dropdown">
                        <i class="glyphicon glyphicon-list"></i><span>Export Fields</span> <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu kv-checkbox-list">
                        <li>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="export_columns_toggle" value="1" checked>
                                    <span class="kv-toggle-all">Toggle All</span>
                                </label>
                            </div>
                        </li>
                        <li class="divider"></li>

                        <li>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="export_columns_selector[]" value="1" checked data-key="1">
                                    ID
                                </label>
                            </div>
                        </li>
                        <li>
                            <div class="checkbox">
                                <label class="disabled">
                                    <input type="checkbox" name="export_columns_selector[]" value="1" checked disabled data-key="2">
                                    Name
                                </label>
                            </div>
                        </li>
                        <li>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="export_columns_selector[]" value="1" checked data-key="3">
                                    CellPhone
                                </label>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="btn-group">
                    <button class="btn btn-default dropdown-toggle" title="Export data in selected format" data-toggle="dropdown">
                        <i class="glyphicon glyphicon-export"></i> Export Data <span class="caret"></span>
                    </button>

                    <ul id="w2" class="dropdown-menu">
                        <li>
                            <a id="w0-txt" class="export-full-txt" href="#" data-format="TXT" tabindex="-1">
                                <i class="text-muted fa fa-file-text-o"></i> Text
                            </a>
                        </li>
                    </ul>
                </div>
            </form>
        </div>
    </div>
    <!-- panel footer -->
    <!--<div class="panel-footer">
    </div>-->
</div>
<!-- Bootstrap Modal -->
<div id="exampleModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>

            <div class="modal-body">
                Example: <input type="text"/>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- ------------------------------------------javascript--------------------------------------------------- -->
<script src="/js/public/jAjaxWidget.js"></script>
<script src="/js/default/index.js"></script>