<link href="/css/common.css" rel="stylesheet"/>
<div class="panel panel-warning">
    <!-- panel heading -->
    <div class="panel-heading">
        <h2>Google Map</h2>
    </div>
    <!-- panel body -->
    <div class="panel-body">
        <div class="row">
            <form class="form-inline">
                <div class="col-sm-12 col-md-12 col-lg-12">
                    Location:&nbsp;&nbsp;<input type="text" id="location" class="form-control" style="width:500px;"/>
                    <button type="button" class="btn btn-primary" id="btb_mark_location">
                        <span class="glyphicon glyphicon-search"></span>Search
                    </button>
                </div>
            </form>
        </div>
        <hr>

        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <div id="map_canvas" class="bill-google-map-canvas">
                </div>
            </div>
        </div>
    </div>
    <!-- panel footer -->
    <!--<div class="panel-footer">
    </div>-->
</div>

<!-- ------------------------------------------javascript--------------------------------------------------- -->
<script src="/js/gmaprepo.js"></script>
<script src="/js/public/util.js"></script>
<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCefZle2DqxF9i51PTfoZsZoOmvWzKYhF4&sensor=true"></script>
<script src="/js/google-map-index.js"></script>