<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <link href="/datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen"/>
        <link href="/css/common.css" rel="stylesheet" />
    </head>
    <body>
        <div class="panel panel-warning">
            <!-- panel heading -->
            <div class="panel-heading">
                <h2>{page_title}</h2>
            </div>
            <!-- panel body -->
            <div class="panel-body">
                <div class="row">
                    <form class="form-inline">
                        <div class="col-sm-10 col-md-10 col-lg-10">
                            关键字: <input type="text" class="form-control" id="keyword"/>
                            <button class="btn btn-primary" type="button" id="btn_search">
                                <span class="glyphicon glyphicon-search"></span>
                                <span>搜索</span>
                            </button>&nbsp;&nbsp;&nbsp;&nbsp;
                            <button class="btn btn-success" type="button" id="btn_add">
                                <span class="glyphicon glyphicon-plus"></span>
                                <span>新增</span>
                            </button>&nbsp;&nbsp;&nbsp;&nbsp;
                            <button class="btn btn-warning" type="button" id="btn_blacklist">
                                <span class="glyphicon glyphicon-warning-sign"></span>
                                <span>黑名单</span>
                            </button>&nbsp;&nbsp;&nbsp;&nbsp;
                            <button class="btn btn-danger" type="button" id="btn_delete">
                                <span class="glyphicon glyphicon-trash"></span>
                                <span>删除</span>
                            </button>&nbsp;&nbsp;&nbsp;&nbsp;
                        </div>
                        <div class="col-sm-2 col-md-2 col-lg-2 text-right">
                            <select name="page_length" id="page_length" class="form-control">
                                <option value="25">25</option>
                                <option value="50">50</option>
                                <option value="75">75</option>
                                <option value="100">100</option>
                            </select>
                            &nbsp;<label>每页</label>
                        </div>
                    </form>
                </div><hr>

                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12">
                        <table class="table table-striped table-bordered bill_table text-center">
                            <tr>
                                <td><input type="checkbox" id="{all_batch_id}" name="{all_batch_id}"/></td>
                                <td>序号</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td>更新时间</td>
                                <td>操作</td>
                            </tr>
                            <tbody>
                            <?php for($i = 0, $len = count($this->data); $i < $len; $i++){ ?>
                                <tr>
                                    <td><input type="checkbox" value="<?php echo $this->data[$i]['{primary_key}']; ?>" name="{batch_id}"/></td>
                                    <td><?php echo ($this->start + $i + 1); ?></td>
                                    <td><?php echo $this->data[$i][1]; ?></td>
                                    <td><?php echo $this->data[$i][2]; ?></td>
                                    <td><?php echo $this->data[$i][3]; ?></td>
                                    <td><?php echo $this->data[$i]['{table_prefix}_update_time']; ?></td>
                                    <td>
                                        <a href="#" id="<?php echo 'modify_' . $this->data[$i]['{primary_key}']; ?>">修改</a>
                                        <a href="#" id="<?php echo 'delete_' . $this->data[$i]['{primary_key}']; ?>">删除</a>
                                    </td>
                                </tr>
                            <?php } ?>

                            <?php if (count($this->data) == 0) { ?>
                                <tr>
                                    <td colspan="5" class="bill_table_no_data">对不起,没有符合条件的数据</td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- panel footer -->
            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-6 col-md-6 col-lg-6 text-left">
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-6 text-right">
                        <ul id="pagination" class="pagination-md"></ul>
                    </div>
                </div>
            </div>
        </div>

        <!-- modal -->
        <div id="add{type_name}Modal" class="modal fade">
            <div class="modal-dialog bill_modal_lg" >
                <div class="modal-content">
                    <div class="modal-header">
                        <span>新增</span>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>

                    <form id="add{type_name}Form" action="#" method="post" enctype="multipart/form-data" class="form-inline">
                        <div class="modal-body">
                            <div class="input-group">
                                <span class="input-group-addon">名称：</span>
                                <input type="text" name="add_{type_name_low_case}_name" id="add_{type_name_low_case}_name" class="form-control"/>
                            </div><br />
                            图片：
                            <input type="file" name="add_{type_name_low_case}_image" id="add_{type_name_low_case}_image" accept="image/*"/><br /><br />
                            <div class="input-group">
                                <span class="input-group-addon">权重：</span>
                                <input type="text" name="add_{type_name_low_case}_weight" id="add_{type_name_low_case}_weight" class="form-control" value='0'/>
                            </div><br />
                            简介：
                            <textarea class="ckeditor" id="ck_add_{type_name_low_case}_intro"></textarea>
                            <input type="hidden" id="add_{type_name_low_case}_intro" name="add_{type_name_low_case}_intro"/>
                        </div>

                        <div class="modal-footer">
                            <button type="submit" class="btn btn-success" id="btn_submit_add">提交</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">关闭</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div id="modify{type_name}Modal" class="modal fade" >
            <div class="modal-dialog bill_modal_lg" >
                <div class="modal-content">
                    <div class="modal-header">
                        <span>修改</span>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <form id="modify{type_name}Form" action="#" method="post" enctype="multipart/form-data" class="form-inline">
                        <div class="modal-body" >
                            <div class="input-group">
                                <span class="input-group-addon">名称：</span>
                                <input type="text" name="modify_{type_name_low_case}_name" id="modify_{type_name_low_case}_name" class="form-control"/>
                            </div><br />
                            图片：
                            <input type="file" name="modify_{type_name_low_case}_image" id="modify_{type_name_low_case}_image" accept="image/*"/><br /><br />
                            <div class="input-group">
                                <span class="input-group-addon">权重：</span>
                                <input type="text" name="modify_{type_name_low_case}_weight" id="modify_{type_name_low_case}_weight" class="form-control" value='0'/>
                            </div><br />
                            简介：
                            <textarea class="ckeditor" id="ck_modify_{type_name_low_case}_intro"></textarea>
                            <input type="hidden" id="modify_{type_name_low_case}_intro" name="modify_{type_name_low_case}_intro"/>
                            <input type="hidden" id="modify_{type_name_low_case}_{primary_key}" name="modify_{type_name_low_case}_{primary_key}"/>
                        </div>

                        <div class="modal-footer">
                            <button type="submit" class="btn btn-success" id="btn_submit_modify">提交</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">关闭</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- ------------------------------------------javascript--------------------------------------------------- -->
        <script src="/bootstrap/js/jquery-1.11.0.min.js"></script>
        <script src="/pagination/jquery.twbsPagination.min.js"></script>
        <script src="/ckeditor/ckeditor.js"></script>
        <script src="/datetimepicker/js/bootstrap-datetimepicker.js" charset="UTF-8"></script>
        <script src="/datetimepicker/js/locales/bootstrap-datetimepicker.zh-CN.js" charset="UTF-8"></script>
        <script src="/js/util.js"></script>
        <script src="/js/common.js"></script>
        <script src="/js/alertInfo.js"></script>
        <script>
        $(document).ready(function(){
            $('#keyword').val('<?php echo $this->keyword; ?>');
            $('#page_length').val(<?php echo $this->page_length; ?>);
        });

        $('#keyword').on('keydown', function(event){
            if (event.keyCode == 13) {
                //enter key
                event.preventDefault();
                $('#btn_search').click();
            }
        });

        $('#btn_search').on('click', function(){
            var keyword = $.trim($('#keyword').val());
            var page_length = <?php echo $this->page_length; ?>;
            search(1, page_length, keyword);
        });

        $('#btn_add').on('click', function(){
            window.add{type_name}Form.reset();
            CKEDITOR.instances.ck_add_{type_name_low_case}_intro.setData('');
            $('#btn_submit_add').attr('disabled', false);
            $('#add{type_name}Modal').modal('show');
        });

        $('#add{type_name}Form').on('submit', (function(event){
            event.preventDefault();

            var error_num = validInput('add');
            if(error_num == 0) {
                $('#btn_submit_add').attr('disabled', true);
                var content = $.trim(CKEDITOR.instances.ck_add_{type_name_low_case}_intro.getData());
                $('#add_{type_name_low_case}_intro').val(content);
                $('#btn_add_{type_name_low_case}').attr('disabled', true);
                var post_url = '/{module_name}/{controller_name}/add{type_name_low_case}';
                var post_data = new FormData(this);
                var msg_success = MESSAGE_ADD_SUCCESS;
                var msg_error = MESSAGE_ADD_ERROR;
                var method = 'post';
                callAjaxWithForm(post_url, post_data, msg_success, msg_error, method);
            }
        }));

        $('a[id^=modify_]').on('click', function(){
            var {primary_key} = $(this).attr('id').substr('modify_'.length);
            var post_url = '/{module_name}/{controller_name}/get{type_name_low_case}';
            var post_data = {
                '{primary_key}' : {primary_key}
            };
            var method = 'get';
            var success_function = function(result){
                $('#modify_{type_name_low_case}_name').val(result.{table_prefix}_name);
                $('#modify_{type_name_low_case}_weight').val(result.{table_prefix}_weight);
                CKEDITOR.instances.ck_modify_{type_name_low_case}_intro.setData(result.{table_prefix}_intro);
                $('#modify_{type_name_low_case}_{primary_key}').val(result.{primary_key});
                $('#btn_submit_modify').attr('disabled', false);
                $('#modify{type_name}Modal').modal('show');
            };
            callAjaxWithFunction(post_url, post_data, success_function, method);
        });

        $('#modify{type_name}Form').on('submit', (function(event){
            event.preventDefault();

            var error_num = validInput('modify');
            if(error_num == 0) {
                $('#btn_submit_modify').attr('disabled', true);
                var content = $.trim(CKEDITOR.instances.ck_modify_{type_name_low_case}_intro.getData());
                $('#modify_{type_name_low_case}_intro').val(content);
                var post_url = '/{module_name}/{controller_name}/modify{type_name_low_case}';
                var post_data = new FormData(this);
                var msg_success = MESSAGE_MODIFY_SUCCESS;
                var msg_error = MESSAGE_MODIFY_ERROR;
                var method = 'post';
                callAjaxWithForm(post_url, post_data, msg_success, msg_error, method);
            }
        }));

        $('a[id^=delete_]').on('click', function(){
            if (confirm(MESSAGE_DELETE_CONFIRM)) {
                var {primary_key} = $(this).attr('id').substr('delete_'.length);
                var url = '/{module_name}/{controller_name}/delete{type_name_low_case}';
                var data = {
                    '{primary_key}' : {primary_key}
                };
                var msg_success = MESSAGE_DELETE_SUCCESS;
                var msg_error = MESSAGE_DELETE_ERROR;
                var method = 'post';
                callAjaxWithAlert(url, data, msg_success, msg_error, method);
            }
        });

        function validInput(type)
        {
            var error_num = 0;
            var name = $.trim($('#' + type + '_{type_name_low_case}_name').val());
            var weight = $('#' + type + '_{type_name_low_case}_weight').val();
            var image = $('#' + type + '_{type_name_low_case}_image').val();
            var content = '';
            if (type == 'add') {
                content = $.trim(CKEDITOR.instances.ck_add_{type_name_low_case}_intro.getData());
            } else if (type == 'modify') {
                content = $.trim(CKEDITOR.instances.ck_modify_{type_name_low_case}_intro.getData());
            }
            if(name == '') {
                error_num = error_num + 1;
                alert(MESSAGE_NAME_ERROR);
            } else if(!isUnsignedInt(weight)) {
                error_num = error_num + 1;
                alert(MESSAGE_WEIGHT_FORMAT_ERROR);
            } else if(type == 'add' && image == '') {
                error_num = error_num + 1;
                alert(MESSAGE_UPLOAD_IMAGE_ERROR);
            } else if(content == '') {
                error_num = error_num + 1;
                alert(MESSAGE_CONTENT_ERROR);
            }

            return error_num;
        }

        /*  --------------------------------------------------------------------------------------------------------  */
        $('.form_date').datetimepicker({
            format: 'yyyy-mm-dd',
            todayBtn:  'linked',
            todayHighlight: 1,
            language: 'zh-CN',
            autoclose: 1,
            minView: 2 //needed, or show time
        });

        $('#{all_batch_id}').on('click', function(){
            batchMute(this, '{batch_id}');
        });

        $('input[name="{batch_id}"]').on('click', function(){
            closeBatch(this, '{all_batch_id}');
        });

        /*  --------------------------------------------------------------------------------------------------------  */
        function search(current_page, page_length, keyword)
        {
            var params = {
                'keyword': keyword || $.trim($('#keyword').val()),
                'current_page': current_page || <?php echo $this->current_page; ?>,
                'page_length': page_length || <?php echo $this->page_length; ?>
            };
            location.href = '/{module_name}/{controller_name}/index?' + $.param(params);
        }

        $('#pagination').twbsPagination({
            totalPages: <?php echo $this->total_pages; ?>,
            startPage: <?php echo $this->current_page; ?>,
            visiblePages: 7,
            first: '首页',
            prev: '上一页',
            next: '下一页',
            last: '尾页',
            onPageClick: function (event, page) {
                search(page);
            }
        });

        $('#page_length').on('change', function(){
            search(1, this.value);
        });
        </script>
    </body>
</html>