<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <link href="/css/common.css" rel="stylesheet" />
    </head>
    <body>
        <div class="panel panel-warning">
            <!-- panel heading -->
            <div class="panel-heading">
                <h2>Finance Category</h2>
            </div>
            <!-- panel body -->
            <div class="panel-body">
                <div class="row">
                    <form action="/person/finance-category/index" method="get" id="formSearch" class="form-inline">
                        <div class="col-sm-10 col-md-10 col-lg-10">
                            分类名: <input type="text" class="form-control" id="keyword" name="keyword"/>
                            <button class="btn btn-primary" type="submit" id="btn_search">
                                <span class="glyphicon glyphicon-search"></span>
                                <span>搜索</span>
                            </button>&nbsp;&nbsp;&nbsp;&nbsp;
                            <button class="btn btn-success" type="button" id="btn_add">
                                <span class="glyphicon glyphicon-plus"></span>
                                <span>新增</span>
                            </button>&nbsp;&nbsp;&nbsp;&nbsp;
                        </div>
                        <div class="col-sm-2 col-md-2 col-lg-2 text-right">
                            <select name="page_length" id="page_length" class="form-control">
                                <option value="25">25</option>
                                <option value="50">50</option>
                                <option value="75">75</option>
                                <option value="100">100</option>
                            </select>
                            &nbsp;<label>每页</label>
                        </div>
                        <input type="hidden" id="current_page" name="current_page"/>
                    </form>
                </div><hr>

                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12">
                        <table class="table table-striped table-bordered bill_table text-center">
                            <tr>
                                <td>序号</td>
                                <td>分类名</td>
                                <td>父级分类名</td>
                                <td>权重</td>
                                <td>更新时间</td>
                                <td>操作</td>
                            </tr>
                            <tbody>
                            <?php for($i = 0, $len = count($this->data); $i < $len; $i++){ ?>
                                <tr>
                                    <td><?php echo ($this->start + $i + 1); ?></td>
                                    <td><?php echo $this->data[$i]['fc_name']; ?></td>
                                    <td>
                                        <?php echo $this->data[$i]['fc_parent_id'] == 0 ?
                                            '无' : $this->parents[$this->data[$i]['fc_parent_id']];
                                        ?>
                                    </td>
                                    <td><?php echo $this->data[$i]['fc_weight']; ?></td>
                                    <td><?php echo $this->data[$i]['fc_update_time']; ?></td>
                                    <td>
                                        <a href="#" id="<?php echo 'modify_' . $this->data[$i]['fc_id']; ?>">修改</a>
                                        <a href="#" id="<?php echo 'delete_' . $this->data[$i]['fc_id']; ?>">删除</a>
                                    </td>
                                </tr>
                            <?php } ?>

                            <?php if (count($this->data) == 0) { ?>
                                <tr>
                                    <td colspan="6" class="bill_table_no_data">对不起,没有符合条件的数据</td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- panel footer -->
            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-6 col-md-6 col-lg-6 text-left">
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-6 text-right">
                        <ul id="pagination" class="pagination-md"></ul>
                    </div>
                </div>
            </div>
        </div>

        <!-- modal -->
        <div id="FinanceCategoryModal" class="modal fade" >
            <div class="modal-dialog bill_modal_sm" >
                <div class="modal-content">
                    <div class="modal-header">
                        <span></span>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <form id="FinanceCategoryForm" action="#" method="post" enctype="multipart/form-data" class="form-inline">
                        <div class="modal-body" >
                            <div class="input-group">
                                <span class="input-group-addon">名称：</span>
                                <input type="text" name="finance_category_name" id="finance_category_name" class="form-control"/>
                            </div><br />
                            <div class="input-group">
                                <span class="input-group-addon">父级分类：</span>
                                <select name="finance_category_parent_id" id="finance_category_parent_id" class="form-control">
                                    <option value="0">无</option>
                                    <?php foreach ($this->parents as $key => $value){ ?>
                                        <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
                                    <?php } ?>
                                </select>
                            </div><br />
                            <div class="input-group">
                                <span class="input-group-addon">权重：</span>
                                <input type="text" name="finance_category_weight" id="finance_category_weight" value="0" class="form-control"/>
                            </div><br />
                            <input type="hidden" id="finance_category_fc_id" name="finance_category_fc_id"/>
                        </div>

                        <div class="modal-footer">
                            <button type="submit" class="btn btn-success" id="btn_submit_finance_category">提交</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">关闭</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- ------------------------------------------javascript--------------------------------------------------- -->
        <script src="/bootstrap/js/jquery-1.11.0.min.js"></script>
        <script src="/pagination/jquery.twbsPagination.min.js"></script>
        <script src="/js/util.js"></script>
        <script src="/js/common.js"></script>
        <script src="/js/alertInfo.js"></script>
        <script>
        $(document).ready(function(){
            $('#keyword').val('<?php echo $this->keyword; ?>');
            $('#page_length').val(<?php echo $this->page_length; ?>);
            $('#current_page').val(<?php echo $this->current_page; ?>);
        });

        $('#btn_add').on('click', function(){
            window.FinanceCategoryForm.reset();
            $('#btn_submit_finance_category').attr('disabled', false);
            $('#FinanceCategoryModal').modal('show');
        });

        $('#FinanceCategoryForm').on('submit', (function(event){
            event.preventDefault();

            var fc_id = $('#finance_category_fc_id').val();
            var type = (fc_id == '') ? 'add' : 'modify';
            var error_num = validInput(type);
            if(error_num == 0) {
                $('#btn_submit_finance_category').attr('disabled', true);
                var post_url = '/person/finance-category/' + type + '-finance-category';
                var post_data = new FormData(this);
                var msg_success = (fc_id == '') ? MESSAGE_ADD_SUCCESS : MESSAGE_MODIFY_SUCCESS;
                var msg_error = (fc_id == '') ? MESSAGE_ADD_ERROR : MESSAGE_MODIFY_ERROR;
                var method = 'post';
                callAjaxWithForm(post_url, post_data, msg_success, msg_error, method);
            }
        }));

        $('a[id^=modify_]').on('click', function(){
            var fc_id = $(this).attr('id').substr('modify_'.length);
            var post_url = '/person/finance-category/get-finance-category';
            var post_data = {
                'fc_id' : fc_id
            };
            var method = 'get';
            var success_function = function(result){
                $('#finance_category_name').val(result.fc_name);
                $('#finance_category_parent_id').val(result.fc_parent_id);
                $('#finance_category_weight').val(result.fc_weight);
                $('#finance_category_fc_id').val(result.fc_id);
                $('#btn_submit_finance_category').attr('disabled', false);
                $('#FinanceCategoryModal').modal('show');
            };
            callAjaxWithFunction(post_url, post_data, success_function, method);
        });

        $('a[id^=delete_]').on('click', function(){
            if (confirm(MESSAGE_DELETE_CONFIRM)) {
                var fc_id = $(this).attr('id').substr('delete_'.length);
                var url = '/person/finance-category/delete-finance-category';
                var data = {
                    'fc_id' : fc_id
                };
                var msg_success = MESSAGE_DELETE_SUCCESS;
                var msg_error = MESSAGE_DELETE_ERROR;
                var method = 'post';
                callAjaxWithAlert(url, data, msg_success, msg_error, method);
            }
        });

        function validInput(type)
        {
            var error_num = 0;
            var name = $.trim($('#finance_category_name').val());
            var weight = $.trim($('#finance_category_weight').val());
            if(name == '') {
                error_num = error_num + 1;
                alert(MESSAGE_NAME_ERROR);
            } else if (!isUnsignedInt(weight)) {
                error_num = error_num + 1;
                alert(MESSAGE_WEIGHT_FORMAT_ERROR);
            }

            return error_num;
        }

        /*  --------------------------------------------------------------------------------------------------------  */
        $('#pagination').twbsPagination({
            totalPages: <?php echo $this->total_pages; ?>,
            startPage: <?php echo $this->current_page; ?>,
            visiblePages: 7,
            first: '首页',
            prev: '上一页',
            next: '下一页',
            last: '尾页',
            onPageClick: function (event, page) {
                $('#current_page').val(page);
                $('#formSearch')[0].submit();
            }
        });

        $('#page_length').on('change', function(){
            $('#current_page').val(1);
            $('#page_length').val(this.value);
            $('#formSearch')[0].submit();
        });

        $('#btn_search').on('click', function(){
            $('#current_page').val(1);
            $('#formSearch')[0].submit();
        });
        </script>
    </body>
</html>