<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link href="/css/common.css" rel="stylesheet"/>
    </head>
    <body>
        <div class="panel panel-warning">
            <!-- panel heading -->
            <div class="panel-heading">
                <h2>Google Map</h2>
            </div>
            <!-- panel body -->
            <div class="panel-body">
                <div class="row">
                    <form class="form-inline">
                        <div class="col-sm-12 col-md-12 col-lg-12">
                            Location:&nbsp;&nbsp;<input type="text" id="location" class="form-control" style="width:500px;"/>
                            <button type="button" class="btn btn-primary" id="btb_mark_location">
                                <span class="glyphicon glyphicon-search"></span>Search
                            </button>
                        </div>
                    </form>
                </div><hr>

                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12">
                        <div id="map_canvas" class="bill-google-map-canvas">
                        </div>
                    </div>
                </div>
            </div>
            <!-- panel footer -->
            <!--<div class="panel-footer">
            </div>-->
        </div>

        <!-- ------------------------------------------javascript--------------------------------------------------- -->
        <script type="text/javascript" src="http://cdn.bootcss.com/jquery/1.11.0/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="/bootstrap/js/jquery-1.11.0.min.js"><\/script>')</script>
        <script src="/js/gmaprepo.js"></script>
        <script src="/js/util.js"></script>
        <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCefZle2DqxF9i51PTfoZsZoOmvWzKYhF4&sensor=true"></script>
        <script>
        $('#location').on('keydown', function(event){
            if (event.keyCode == 13) {
                $('#btb_mark_location').click();
            }
        });

        $('#btb_mark_location').on('click', function(){
            var location = $.trim($('#location').val());
            if(location != '') {
                var get_url = '/googlemap/marklocation';
                var get_data = {
                    'location' : location
                };
                var method = 'get';
                var success_function = function(coordinate_result){
                    console.log(coordinate_result);
                    if(coordinate_result == '') {
                        alert('error info');
                    } else {
                        showPosition(coordinate_result.Longitude, coordinate_result.Latitude);
                    }
                };
                callAjaxWithFunction(get_url, get_data, success_function, method);
            } else {
                alert('location can\'t be empty');
            }
        });
        </script>
    </body>
</html>