<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link href="/css/common.css" rel="stylesheet"/>
    </head>
    <body>
        <div class="panel panel-warning">
            <!-- panel heading -->
            <div class="panel-heading">
                <h2>Multiple Markers with not cluster & cluster</h2>
            </div>
            <!-- panel body -->
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12">
                        <div id="map_canvas_nocluster" class="bill-google-map-canvas"></div>
                        <div id="map_canvas_cluster" class="bill-google-map-canvas bill-margin-left"></div>
                    </div>
                </div>
            </div>
            <!-- panel footer -->
            <!--<div class="panel-footer">
            </div>-->
        </div>

        <!-- ------------------------------------------javascript--------------------------------------------------- -->
        <script type="text/javascript" src="http://libs.baidu.com/jquery/1.11.0/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="/bootstrap/js/jquery-1.11.0.min.js"><\/script>')</script>
        <script src="/js/gmaprepo.js"></script>
        <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCefZle2DqxF9i51PTfoZsZoOmvWzKYhF4&sensor=true"></script>
        <script src="/js/markerclusterer.js"></script>
        <script>
        $(document).ready(function(){
            plotMarkers();
        });

        function plotMarkers()
        {
            var lng_lat = <?php echo $this->lng_lat; ?>;
            markMultiPosition(lng_lat, 'map_canvas_nocluster');
            markMultiPostionAndCluster(lng_lat, 'map_canvas_cluster');
        }
        </script>
    </body>
</html>
