<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <title>执行结果</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="refresh" content="0;URL=/index" />
    </head>
    
    <body>
        <h1>
            <script>
                <?php if($this->ret == 0) {?>
                    alert('用户名或者密码错误！');
                <?php } ?>
            </script>
        </h1>
    </body>
</html>