<link href="/datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen"/>
<link href="/css/common.css" rel="stylesheet" />
<div class="panel panel-warning">
    <!-- panel heading -->
    <div class="panel-heading">
        <h2>Dream history</h2>
    </div>
    <!-- panel body -->
    <div class="panel-body">
        <div class="row">
            <form action="#" method="get" id="formSearch" class="form-inline">
            <div class="col-sm-10 col-md-10 col-lg-10">
                Keyword: <input type="text" class="form-control" id="keyword" name="keyword"/>
                <button class="btn btn-primary" type="submit" id="btn_search">
                    <span class="glyphicon glyphicon-search"></span>
                    <span>搜索</span>
                </button>&nbsp;&nbsp;&nbsp;&nbsp;
                <button class="btn btn-success" type="button" id="btn_add">
                    <span class="glyphicon glyphicon-plus"></span>
                    <span>新增</span>
                </button>&nbsp;&nbsp;&nbsp;&nbsp;
            </div>
            <div class="col-sm-2 col-md-2 col-lg-2 text-right">
                <select name="page_length" id="page_length" class="form-control">
                    <option value="25">25</option>
                    <option value="50">50</option>
                    <option value="75">75</option>
                    <option value="100">100</option>
                </select>
                &nbsp;<label>每页</label>
            </div>
                <input type="hidden" id="current_page" name="current_page"/>
            </form>
        </div><hr>

        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <table id="tbl" class="table table-striped table-bordered bill_table text-center">
                    <thead>
                        <tr>
                            <td>序号</td>
                            <td>日期</td>
                            <td>次数</td>
                            <td>创建时间</td>
                            <td>更新时间</td>
                            <td>操作</td>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- panel footer -->
    <div class="panel-footer">
        <div class="row">
            <div class="col-sm-6 col-md-6 col-lg-6 text-left">
            </div>
            <div class="col-sm-6 col-md-6 col-lg-6 text-right">
                <ul id="pagination" class="pagination-md"></ul>
            </div>
        </div>
    </div>
</div>
<!-- modal -->
<div id="DreamHistoryModal" class="modal fade">
    <div class="modal-dialog bill_modal_sm" >
        <div class="modal-content">
            <div class="modal-header"><span>Dream history</span>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>

            <form id="DreamHistoryForm" action="#" method="post" enctype="multipart/form-data" class="form-inline">
                <div class="modal-body">
                    <div class="input-group">
                        <span class="input-group-addon">日期：</span>
                        <input type="text" name="dream_history_date" id="dream_history_date" class="form-control form_date"/>
                    </div><br />
                    <div class="input-group">
                        <span class="input-group-addon">次数：</span>
                        <input type="text" name="dream_history_count" id="dream_history_count" class="form-control"/>
                    </div><br />
                    <input type="hidden" name="dream_history_id" id="dream_history_id"/>
                </div>

                <div class="modal-footer">
                    <button type="submit" class="btn btn-success" id="btn_submit_dream_history">提交</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">关闭</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- ------------------------------------------javascript--------------------------------------------------- -->
<script src="/pagination/jquery.twbsPagination.min.js"></script>
<script src="/datetimepicker/js/bootstrap-datetimepicker.js" charset="UTF-8"></script>
<script src="/datetimepicker/js/locales/bootstrap-datetimepicker.zh-CN.js" charset="UTF-8"></script>
<script src="/js/datetimepicker.js"></script>
<script src="/js/util.js"></script>
<script src="/js/alertInfo.js"></script>
<script src="/js/dream-history.js"></script>