<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <link href="/css/common.css" rel="stylesheet" />
    </head>
    <body>
        <div class="panel panel-warning">
            <!-- panel heading -->
            <div class="panel-heading">
                <h2>BackendLog</h2>
            </div>
            <!-- panel body -->
            <div class="panel-body">
                <div class="row">
                    <form action="/person/backend-log/index" method="get" id="formSearch" class="form-inline">
                        <div class="col-sm-10 col-md-10 col-lg-10">
                            关键字: <input type="text" class="form-control" id="keyword" name="keyword"/>
                            <button class="btn btn-primary" type="submit" id="btn_search">
                                <span class="glyphicon glyphicon-search"></span>
                                <span>搜索</span>
                            </button>&nbsp;&nbsp;&nbsp;&nbsp;
                            <button class="btn btn-success" type="button" id="btn_add">
                                <span class="glyphicon glyphicon-plus"></span>
                                <span>新增</span>
                            </button>&nbsp;&nbsp;&nbsp;&nbsp;
                        </div>
                        <div class="col-sm-2 col-md-2 col-lg-2 text-right">
                            <select name="page_length" id="page_length" class="form-control">
                                <option value="25">25</option>
                                <option value="50">50</option>
                                <option value="75">75</option>
                                <option value="100">100</option>
                            </select>
                            &nbsp;<label>每页</label>
                        </div>
                        <input type="hidden" id="current_page" name="current_page"/>
                    </form>
                </div><hr>
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12">
                        <table class="table table-striped table-bordered bill_table text-center">
                            <tr>                                
                                <td>序号</td>
                                <td>SQL</td>
                                <td>Operator</td>
                                <td>create time</td>
                                <td>update time</td>
                                <td>操作</td>
                            </tr>
                            <tbody>
                            <?php for($i = 0, $len = count($this->data); $i < $len; $i++){ ?>
                                <tr>                                    
                                    <td><?php echo ($this->js_data['start'] + $i + 1); ?></td>
                                    <td><?php echo $this->data[$i]['content']; ?></td>
                                    <td><?php echo $this->data[$i]['name']; ?></td>
                                    <td><?php echo $this->data[$i]['create_time']; ?></td>
                                    <td><?php echo $this->data[$i]['update_time']; ?></td>
                                    <td>
                                        <a href="#" id="<?php echo 'modify_' . $this->data[$i]['blid']; ?>">修改</a>
                                        <a href="#" id="<?php echo 'delete_' . $this->data[$i]['blid']; ?>">删除</a>
                                    </td>
                                </tr>
                            <?php } ?>
                            <?php if (count($this->data) == 0) { ?>
                                <tr>
                                    <td colspan="6" class="bill_table_no_data">对不起,没有符合条件的数据</td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- panel footer -->
            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-6 col-md-6 col-lg-6 text-left">
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-6 text-right">
                        <ul id="pagination" class="pagination-md"></ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- ------------------------------------------javascript--------------------------------------------------- -->
        <script src="/pagination/jquery.twbsPagination.min.js"></script>
        <script src="/js/util.js"></script>
        <script src="/js/common.js"></script>
        <script>
        var js_data = <?php echo json_encode($this->js_data); ?>;
        $(document).ready(function(){
            $('#keyword').val(js_data.keyword);
            $('#page_length').val(js_data.page_length);
            $('#current_page').val(js_data.current_page);
        });

        /*  --------------------------------------------------------------------------------------------------------  */
        $('#pagination').twbsPagination({
            totalPages: js_data.total_pages,
            startPage: js_data.current_page,
            visiblePages: 7,
            first: '首页',
            prev: '上一页',
            next: '下一页',
            last: '尾页',
            onPageClick: function (event, page) {
                $('#current_page').val(page);
                $('#formSearch')[0].submit();
            }
        });

        $('#page_length').on('change', function(){
            $('#current_page').val(1);
            $('#page_length').val(this.value);
            $('#formSearch')[0].submit();
        });

        $('#btn_search').on('click', function(){
            $('#current_page').val(1);
            $('#formSearch')[0].submit();
        });
        </script>
    </body>
</html>