<link href="/assets/datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen"/>
<link href="/css/common.css" rel="stylesheet" />
<div class="panel panel-warning">
    <!-- panel heading -->
    <div class="panel-heading">
        <h2>Finance History</h2>
    </div>
    <!-- panel body -->
    <div class="panel-body">
        <div class="row">
        </div><hr>

        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <span class="bill_font_bold_green">All payment history data by day</span>
                <div class="bill-chart-canvas_all">
                    <canvas id="payment_history_line_chart_all"></canvas>
                </div>
            </div>

            <span class="bill-margin-left bill_font_bold_green">All category payment history data in last 30 days</span>
            <span id="month_spent"></span>
            <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="bill-chart-canvas">
                    <canvas id="month_category_payment_history_line_chart"></canvas>
                </div>
                <div class="bill-chart-canvas bill-margin-left">
                    <canvas id="month_category_payment_history_bar_chart"></canvas>
                </div>
            </div>

            <br/>

            <span class="bill-margin-left bill_font_bold_green">All payment history data by month</span>
            <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="bill-chart-canvas">
                    <canvas id="payment_history_line_chart"></canvas>
                </div>
                <div class="bill-chart-canvas bill-margin-left">
                    <canvas id="payment_history_bar_chart"></canvas>
                </div>
            </div>

            <br/>

            <span class="bill-margin-left bill_font_bold_green">All category payment history data in last one year</span>
            <span id="year_spent"></span>
            <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="bill-chart-canvas">
                    <canvas id="category_payment_history_line_chart"></canvas>
                </div>
                <div class="bill-chart-canvas bill-margin-left">
                    <canvas id="category_payment_history_bar_chart"></canvas>
                </div>
            </div>
        </div>
    </div>
    <!-- panel footer -->
    <!--<div class="panel-footer">
    </div>-->
</div>

<!-- ------------------------------------------javascript--------------------------------------------------- -->
<script src="/assets/datetimepicker/js/bootstrap-datetimepicker.js" charset="UTF-8"></script>
<script src="/assets/datetimepicker/js/locales/bootstrap-datetimepicker.zh-CN.js" charset="UTF-8"></script>
<script src="/assets/chart.js/Chart.min.js"></script>
<script src="/js/datetimepicker.js"></script>
<script src="/js/util.js"></script>
<script>
$(document).ready(function(){
    //payment history data by month
    initMonthChart();
    //all payment history data by day
    initLineChartAll();
    //payment by category last year
    initYearCategoryChart();
    //payment by category last 30 days
    initMonthCategoryChart();
});

function initMonthChart()
{
    var chart_data = <?php echo $this->chart_data; ?>;
    var data_period = chart_data['period'];
    var data_payment = chart_data['payment'];
    var line_canvas_id = 'payment_history_line_chart';
    var bar_canvas_id = 'payment_history_bar_chart';
    if (data_period.length != 0) {
        initLineChart(data_period, data_payment, line_canvas_id);
        initBarChart(data_period, data_payment, bar_canvas_id);
    }
}

function initYearCategoryChart()
{
    var category_chart_data = <?php echo $this->year_category_chart_data; ?>;
    var data_category = category_chart_data['category'];
    var data_payment = category_chart_data['payment'];
    $('#year_spent').text('(' + <?php echo $this->year_spent; ?> + ')');
    var line_canvas_id = 'category_payment_history_line_chart';
    var bar_canvas_id = 'category_payment_history_bar_chart';
    if (data_category.length != 0) {
        initLineChart(data_category, data_payment, line_canvas_id);
        initBarChart(data_category, data_payment, bar_canvas_id);
    }
}

function initMonthCategoryChart()
{
    var category_chart_data = <?php echo $this->month_category_chart_data; ?>;
    var data_category = category_chart_data['category'];
    var data_payment = category_chart_data['payment'];
    $('#month_spent').text('(' + <?php echo $this->month_spent; ?> + ')');
    var line_canvas_id = 'month_category_payment_history_line_chart';
    var bar_canvas_id = 'month_category_payment_history_bar_chart';
    if (data_category.length != 0) {
        initLineChart(data_category, data_payment, line_canvas_id);
        initBarChart(data_category, data_payment, bar_canvas_id);
    }
}

function initLineChartAll()
{
    var chart_data = <?php echo $this->all_chart_data; ?>;
    var data_period = chart_data['period'];
    var data_payment = chart_data['payment'];
    if (data_period.length != 0) {
        var line_data = {
            labels : data_period,
            datasets: [
                {
                    fillColor: "rgba(151,187,205,0.2)",
                    strokeColor: "rgba(151,187,205,1)",
                    pointColor: "rgba(151,187,205,1)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(220,220,220,1)",
                    data: data_payment
                }
            ]
        };
        var line_option = {
            responsive: true
        };
        var chart_line_canvas = document.getElementById("payment_history_line_chart_all").getContext("2d");
        var chart_line = new Chart(chart_line_canvas).Line(line_data, line_option);
    }
}

function initLineChart(data_x_labels, data_y_axis, line_canvas_id)
{
    var line_data = {
        labels : data_x_labels,
        datasets: [
            {
                fillColor: "rgba(151,187,205,0.2)",
                strokeColor: "rgba(151,187,205,1)",
                pointColor: "rgba(151,187,205,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                pointHighlightStroke: "rgba(220,220,220,1)",
                data: data_y_axis
            }
        ]
    };
    var line_option = {
        responsive: true
    };
    var chart_line_canvas = document.getElementById(line_canvas_id).getContext("2d");
    var chart_line = new Chart(chart_line_canvas).Line(line_data, line_option);
}

function initBarChart(data_x_labels, data_y_axis, bar_canvas_id)
{
    var bar_data = {
        labels : data_x_labels,
        datasets: [
            {
                fillColor: "rgba(151,187,205,0.2)",
                strokeColor: "rgba(151,187,205,1)",
                pointColor: "rgba(151,187,205,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                pointHighlightStroke: "rgba(220,220,220,1)",
                data: data_y_axis
            }
        ]
    };
    var bar_option = {
        responsive: true
    };
    var chart_bar_canvas = document.getElementById(bar_canvas_id).getContext("2d");
    var chart_bar = new Chart(chart_bar_canvas).Bar(bar_data, bar_option);
}

$('#btn_search').on('click', function(){

});

/*  --------------------------------------------------------------------------------------------------------  */
function search(keyword)
{

}
</script>