<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <link href="/datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen"/>
        <link href="/css/common.css" rel="stylesheet" />
    </head>
    <body>
        <div class="panel panel-warning">
            <!-- panel heading -->
            <div class="panel-heading">
                <h2>消费历史管理</h2>
            </div>
            <!-- panel body -->
            <div class="panel-body">
                <div class="row">
                    <form class="form-inline">
                        <div class="col-sm-10 col-md-10 col-lg-10">
                            日期: <input type="text" class="form-control form_date" id="payment_date"/>
                            <button class="btn btn-primary" type="button" id="btn_search">
                                <span class="glyphicon glyphicon-search"></span>
                                <span>搜索</span>
                            </button>&nbsp;&nbsp;&nbsp;&nbsp;
                            <button class="btn btn-success" type="button" id="btn_add">
                                <span class="glyphicon glyphicon-plus"></span>
                                <span>新增</span>
                            </button>&nbsp;&nbsp;&nbsp;&nbsp;
                        </div>
                        <div class="col-sm-2 col-md-2 col-lg-2 text-right">
                            <select name="page_length" id="page_length" class="form-control">
                                <option value="25">25</option>
                                <option value="50">50</option>
                                <option value="75">75</option>
                                <option value="100">100</option>
                            </select>
                            &nbsp;<label>每页</label>
                        </div>
                    </form>
                </div><hr>

                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12">
                        <table class="table table-striped table-bordered bill_table text-center">
                            <tr>
                                <td>序号</td>
                                <td>日期</td>
                                <td>消费金额</td>
                                <td>分类</td>
                                <td>备注</td>
                                <td>更新时间</td>
                                <td>操作</td>
                            </tr>
                            <tbody>
                            <?php for($i = 0, $len = count($this->data); $i < $len; $i++){ ?>
                                <tr>
                                    <td><?php echo ($this->start + $i + 1); ?></td>
                                    <td><?php echo $this->data[$i]['fp_payment_date']; ?></td>
                                    <td><?php echo $this->data[$i]['fp_payment']; ?></td>
                                    <td><?php echo $this->data[$i]['category']; ?></td>
                                    <td><?php echo $this->data[$i]['fp_detail']; ?></td>
                                    <td><?php echo $this->data[$i]['fp_update_time']; ?></td>
                                    <td>
                                        <a href="#" id="<?php echo 'modify_' . $this->data[$i]['fp_id']; ?>">修改</a>
                                        <a href="#" id="<?php echo 'delete_' . $this->data[$i]['fp_id']; ?>">删除</a>
                                    </td>
                                </tr>
                            <?php } ?>

                            <?php if (count($this->data) == 0) { ?>
                                <tr>
                                    <td colspan="7" class="bill_table_no_data">对不起,没有符合条件的数据</td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- panel footer -->
            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-6 col-md-6 col-lg-6 text-left">
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-6 text-right">
                        <ul id="pagination" class="pagination-md"></ul>
                    </div>
                </div>
            </div>
        </div>

        <!-- modal -->
        <div id="addFinancepaymentModal" class="modal fade">
            <div class="modal-dialog bill_modal_md" >
                <div class="modal-content">
                    <div class="modal-header">
                        <span>新增</span>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>

                    <form id="addFinancepaymentForm" action="#" method="post" enctype="multipart/form-data" class="form-inline">
                        <div class="modal-body">
                            <div class="input-group">
                                <span class="input-group-addon">日期：</span>
                                <input type="text"
                                       name="add_financepayment_payment_date"
                                       id="add_financepayment_payment_date"
                                       class="form-control form_date"
                                />
                            </div><br />
                            <div class="input-group">
                                <span class="input-group-addon">金额：</span>
                                <input type="text"
                                       name="add_financepayment_payment"
                                       id="add_financepayment_payment"
                                       class="form-control"
                                       value='0'
                                />
                            </div><br />
                            <div class="input-group">
                                <span class="input-group-addon">分类：</span>
                                <select id="add_financepayment_fc_parent_id" class="form-control">
                                    <?php foreach($this->parent_categories as $key => $value){ ?>
                                        <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
                                    <?php } ?>
                                </select>
                                <select name="add_financepayment_fc_id" id="add_financepayment_fc_id" class="form-control">
                                </select>
                            </div><br />
                            <div class="input-group">
                                <span class="input-group-addon">备注：</span>
                                <textarea id="add_financepayment_intro" name="add_financepayment_intro" class="bill_textarea_full"></textarea>
                            </div><br />
                        </div>

                        <div class="modal-footer">
                            <button type="submit" class="btn btn-success" id="btn_submit_add">提交</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">关闭</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div id="modifyFinancepaymentModal" class="modal fade" >
            <div class="modal-dialog bill_modal_md" >
                <div class="modal-content">
                    <div class="modal-header">
                        <span>修改</span>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <form id="modifyFinancepaymentForm" action="#" method="post" enctype="multipart/form-data" class="form-inline">
                        <div class="modal-body" >
                            <div class="input-group">
                                <span class="input-group-addon">日期：</span>
                                <input type="text"
                                       name="modify_financepayment_payment_date"
                                       id="modify_financepayment_payment_date"
                                       class="form-control form_date"
                                />
                            </div><br />
                            <div class="input-group">
                                <span class="input-group-addon">金额：</span>
                                <input type="text"
                                       name="modify_financepayment_payment"
                                       id="modify_financepayment_payment"
                                       class="form-control"
                                       value='0'
                                />
                            </div><br />
                            <div class="input-group">
                                <span class="input-group-addon">分类：</span>
                                <select id="modify_financepayment_fc_parent_id" class="form-control">
                                    <?php foreach($this->parent_categories as $key => $value){ ?>
                                        <option value="<?php echo $key; ?>"><?php echo $value; ?></option>
                                    <?php } ?>
                                </select>
                                <select name="modify_financepayment_fc_id" id="modify_financepayment_fc_id" class="form-control">
                                </select>
                            </div><br />
                            <div class="input-group">
                                <span class="input-group-addon">备注：</span>
                                <textarea id="modify_financepayment_intro" name="modify_financepayment_intro" class="bill_textarea_full"></textarea>
                            </div><br />
                            <input type="hidden" id="modify_financepayment_fp_id" name="modify_financepayment_fp_id"/>
                        </div>

                        <div class="modal-footer">
                            <button type="submit" class="btn btn-success" id="btn_submit_modify">提交</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">关闭</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- ------------------------------------------javascript--------------------------------------------------- -->
        <script type="text/javascript" src="http://cdn.bootcss.com/jquery/1.11.0/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="/bootstrap/js/jquery-1.11.0.min.js"><\/script>')</script>
        <script src="/pagination/jquery.twbsPagination.min.js"></script>
        <script src="/datetimepicker/js/bootstrap-datetimepicker.js" charset="UTF-8"></script>
        <script src="/datetimepicker/js/locales/bootstrap-datetimepicker.zh-CN.js" charset="UTF-8"></script>
        <script src="/js/util.js"></script>
        <script src="/js/common.js"></script>
        <script src="/js/alertInfo.js"></script>
        <script>
        $(document).ready(function(){
            $('#payment_date').val('<?php echo $this->payment_date; ?>');
            $('#page_length').val(<?php echo $this->page_length; ?>);
        });

        $('#payment_date').on('keydown', function(event){
            if (event.keyCode == 13) {
                //enter key
                event.preventDefault();
                $('#btn_search').click();
            }
        });

        $('#btn_search').on('click', function(){
            var payment_date = $.trim($('#payment_date').val());
            var current_page = <?php echo $this->current_page; ?>;
            var page_length = <?php echo $this->page_length; ?>;
            search(current_page, page_length, payment_date);
        });

        $('#btn_add').on('click', function(){
            window.addFinancepaymentForm.reset();
            $('#add_financepayment_payment_date').val(getCurrentDate());
            $('#btn_submit_add').attr('disabled', false);
            var parent_id = $('#add_financepayment_fc_parent_id').val();
            var select_id = 'add_financepayment_fc_id';
            var addition_function = function(){
                $('#addFinancepaymentModal').modal('show');
            };
            getFinanceSubcategory(parent_id, select_id, addition_function);
        });

        $('#add_financepayment_fc_parent_id').on('change', function(){
            var parent_id = this.value;
            var select_id = 'add_financepayment_fc_id';
            getFinanceSubcategory(parent_id, select_id);
        });

        function getFinanceSubcategory(parent_id, select_id, addition_function)
        {
            var post_url = '/person/financecategory/getfinancesubcategory';
            var post_data = {
                'parent_id': parent_id
            };
            var method = 'post';
            var success_function = function(result){
                var content = '';
                for(var fc_id in result) {
                    content += '<option value="' + fc_id + '">' + result[fc_id] + '</option>';
                }
                $('#' + select_id).empty().append(content);
                if (typeof addition_function != 'undefined') {
                    addition_function();
                }
            };
            callAjaxWithFunction(post_url, post_data, success_function, method);
        }

        $('#addFinancepaymentForm').on('submit', (function(event){
            event.preventDefault();

            var error_num = validInput('add');
            if(error_num == 0) {
                $('#btn_submit_add').attr('disabled', true);
                $('#btn_add_financepayment').attr('disabled', true);
                var post_url = '/person/financepayment/addfinancepayment';
                var post_data = new FormData(this);
                var msg_success = MESSAGE_ADD_SUCCESS;
                var msg_error = MESSAGE_ADD_ERROR;
                var method = 'post';
                callAjaxWithForm(post_url, post_data, msg_success, msg_error, method);
            }
        }));

        $('a[id^=modify_]').on('click', function(){
            var fp_id = $(this).attr('id').substr('modify_'.length);
            var post_url = '/person/financepayment/getfinancepayment';
            var post_data = {
                'fp_id' : fp_id
            };
            var method = 'post';
            var success_function = function(result){
                var select_id = 'modify_financepayment_fc_id';
                getFinanceSubcategory(result.fc_parent_id, select_id);
                $('#modify_financepayment_payment_date').val(result.fp_payment_date);
                $('#modify_financepayment_payment').val(result.fp_payment);
                $('#modify_financepayment_fc_parent_id').val(result.fc_parent_id);
                $('#modify_financepayment_intro').val(result.fp_detail);
                $('#modify_financepayment_fp_id').val(result.fp_id);
                $('#btn_submit_modify').attr('disabled', false);
                $('#modifyFinancepaymentModal').modal('show');
            };
            callAjaxWithFunction(post_url, post_data, success_function, method);
        });

        $('#modify_financepayment_fc_parent_id').on('change', function(){
            var parent_id = this.value;
            var select_id = 'modify_financepayment_fc_id';
            getFinanceSubcategory(parent_id, select_id);
        });

        $('#modifyFinancepaymentForm').on('submit', (function(event){
            event.preventDefault();

            var error_num = validInput('modify');
            if(error_num == 0) {
                $('#btn_submit_modify').attr('disabled', true);
                var post_url = '/person/financepayment/modifyfinancepayment';
                var post_data = new FormData(this);
                var msg_success = MESSAGE_MODIFY_SUCCESS;
                var msg_error = MESSAGE_MODIFY_ERROR;
                var method = 'post';
                callAjaxWithForm(post_url, post_data, msg_success, msg_error, method);
            }
        }));

        $('a[id^=delete_]').on('click', function(){
            if (confirm(MESSAGE_DELETE_CONFIRM)) {
                var fp_id = $(this).attr('id').substr('delete_'.length);
                var url = '/person/financepayment/deletefinancepayment';
                var data = {
                    'fp_id' : fp_id
                };
                var msg_success = MESSAGE_DELETE_SUCCESS;
                var msg_error = MESSAGE_DELETE_ERROR;
                var method = 'post';
                callAjaxWithAlert(url, data, msg_success, msg_error, method);
            }
        });

        function validInput(type)
        {
            var error_num = 0;
            var payment_date = $.trim($('#' + type + '_financepayment_payment_date').val());
            var payment = $('#' + type + '_financepayment_payment').val();
            if(payment_date == '') {
                error_num = error_num + 1;
                alert(MESSAGE_DATE_ERROR);
            } else if(!isUnsignedFloat(payment)) {
                error_num = error_num + 1;
                alert(MESSAGE_MONEY_FORMAT_ERROR);
            }

            return error_num;
        }

        /*  --------------------------------------------------------------------------------------------------------  */
        $('.form_date').datetimepicker({
            format: 'yyyy-mm-dd',
            todayBtn:  'linked',
            todayHighlight: 1,
            language: 'zh-CN',
            autoclose: 1,
            minView: 2 //needed, or show time
        });

        /*  --------------------------------------------------------------------------------------------------------  */
        function search(current_page, page_length, payment_date)
        {
            var params = {
                'payment_date': payment_date || $.trim($('#payment_date').val()),
                'current_page': current_page || <?php echo $this->current_page; ?>,
                'page_length': page_length || <?php echo $this->page_length; ?>
            };
            location.href = '/person/financepayment/index?' + $.param(params);
        }

        $('#pagination').twbsPagination({
            totalPages: <?php echo $this->total_pages; ?>,
            startPage: <?php echo $this->current_page; ?>,
            visiblePages: 7,
            first: '首页',
            prev: '上一页',
            next: '下一页',
            last: '尾页',
            onPageClick: function (event, page) {
                search(page);
            }
        });

        $('#page_length').on('change', function(){
            search(1, this.value);
        });
        </script>
    </body>
</html>