<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>

    <body>
        <div style="min-height:700px;">
            <h3 style="margin-top:20%;" class="text-center">
                欢迎进入后台管理系统
            </h3>
        </div>
    </body>
</html>

