<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />    
    </head>
    <body>
        <div class="panel panel-warning">
            <!-- panel heading -->
            <div class="panel-heading">
                <h2>修改密码</h2>
            </div>
            <!-- panel body -->
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-1 col-md-1 col-lg-1"></div>
                    <div class="col-sm-4 col-md-4 col-lg-4 text-left">
                        <form name="modifypasswordform" id="modifypasswordform" action="/main/modify-password" method="post" class="form-inline">
                            <div class="form-group">
                                <span>原密码：</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <input type="password" name="old_password" id="old_password" class="form-control" autofocus/>
                            </div>
                            <br/><br/>
                            <div class="form-group">
                                <span>新密码：</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <input type="password" name="new_password" id="new_password" class="form-control"/>

                            </div>
                            <br/><br/>
                            <div class="form-group">
                                <span>新密码确认：</span>
                                <input type="password" name="new_password_repeat" id="new_password_repeat" class="form-control"/>
                            </div>
                            <br/><br/>
                            <div class="form-group">
                                <button type="submit" class="btn btn-success" id="btn_modify_password">确认修改</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- panel footer -->
            <!--<div class="panel-footer">
            </div>-->
        </div>

        <script src="/bootstrap/js/jquery-1.11.0.min.js" charset="UTF-8"></script>
        <script src="/bootstrap/js/bootstrap.min.js" charset="UTF-8"></script>
        <script>
        $(document).ready(function(){
            $('#old_password').val('');
        });
        $('#modifypasswordform').on('submit', function(event){
            event.preventDefault();
            modifyPassword();
        });

        function modifyPassword()
        {
            var old_password = $.trim($('#old_password').val());
            var new_password = $.trim($('#new_password').val());
            var new_password_repeat = $.trim($('#new_password_repeat').val());

            if (old_password == '') {
                alert('密码不能为空！');
            } else if (new_password == '') {
                alert('新密码不能为空！');
            } else if (new_password_repeat == '') {
                alert('新密码确认不能为空！');
            } else if (new_password != new_password_repeat) {
                alert('两次密码不相同');
            } else {
                $('#modifypasswordform').get(0).submit();
            }
        }
        </script>
    </body>
</html>
