<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="zh-cn">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="stylesheet" type="text/css"  href="/css/login.css" />
        <title>后台</title>
    </head>
    <body>
        <div class="login">
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>
