<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="zh-cn">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link href="Favicon.ico" rel="icon" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="/css/login.css"/>
    <link href="/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet"/>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="/assets/compatible/html5shiv.min.js"></script>
    <script src="/assets/compatible/respond.min.js"></script>
    <![endif]-->
    <title>后台</title>
</head>

<body>
<div class="login">
    <?php echo $this->layout()->content; ?>
</div>
</body>
</html>