<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta charset="utf-8">
        <title>Bill Coderepo</title>

        <!-- Bootstrap core CSS -->
        <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet"/>
        <link href="/css/layout.css" rel="stylesheet"/>
    </head>

    <body>
        <div class="navbar navbar-default navbar-fixed-top">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Bill</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown active">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Variety<b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/index/index">Other</a></li>
                            <li><a href="/demo/index">Demo</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Map
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/googlemap">Google Map</a></li>
                            <li><a href="/googlemap/multiplelocation">Multiple Markes</a></li>
                            <li><a href="#">Baidu Map</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Person<b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/person/dreamhistory/index">Dream History</a></li>
                            <li><a href="/person/dreamhistorychart/index">Dream History Chart</a></li>
                            <li><a href="/person/badhistory/index">Bad History</a></li>
                            <li><a href="/person/badhistorychart/index">Bad History Chart</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row bill-layout-width">
            <div class="col-sm-3 col-md-3 col-lg-2 well bill-sidebar" id="main">
                <ul class="nav nav-sidebar">
                </ul>
            </div>
            <!-- below is for show action view phtml file. -->
            <div class="col-sm-9 col-md-9 col-lg-10 bill-content">
                <?php echo $this->layout()->content;?>
            </div>
        </div>

        <div class="footer bill-footer">
            <div class="container text-center">
                <p class="text-muted">
                    Released under <a href="http://apache.org/licenses/LICENSE-2.0.html" target="_blank">Apache 2.0</a>
                    Copyright 2014, Bill.
                </p>
            </div>
        </div>

        <!-- Placed at the end of the document so the pages load faster -->
        <script src="/bootstrap/js/jquery-1.11.0.min.js"></script>
        <script src="/bootstrap/js/bootstrap.min.js"></script>
        <script src="/bootstrap/js/jquery.cookie.js"></script>
        <script>
        $(document).ready(function(){
            var li_content = '';
            var cookie_href = $.cookie('nav-top');
            if (typeof cookie_href == 'undefined') {
                li_content = $('ul.nav.navbar-nav li').find('.active');
            } else {
                $('ul.nav.navbar-nav li ul li').children('a').each(function(){
                    if (cookie_href == $(this).attr('href')) {
                        $(this).parent().parent().parent().addClass('active') //set current class active
                            .siblings().removeClass('active'); //remove brother class active
                        //get active ul li
                        li_content = $(this).parent().siblings().andSelf();
                    }
                });
            }
            //console.log(li_content);
            if (li_content != '') {
                li_content.appendTo('#main > ul, ul.nav.navbar-nav li.dropdown.active ul.dropdown-menu');
                //notice: below will failed, only one element is append
                //referrence:http://stackoverflow.com/questions/3636401/jquery-append-to-multiple-elements-fails
                /*$('ul.nav.navbar-nav li.dropdown.active ul.dropdown-menu').append(li_content);
                $('#main > ul').empty().append(li_content);*/
            }
        });

        $('ul.nav.navbar-nav li ul li a').on('click', function(){
            var href = $(this).attr('href');
            $.cookie('nav-top', href, {expires : 1, path : '/'});
        });
        </script>
    </body>
</html>