<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <link href="/css/common.css" rel="stylesheet" />
    </head>
    <body>
        <div class="panel panel-warning">
            <!-- panel heading -->
            <div class="panel-heading">
                <h2>Demo</h2>
            </div>
            <!-- panel body -->
            <div class="panel-body">
                <div class="row">
                    <form class="form-inline">
                    <div class="col-sm-10 col-md-10 col-lg-10">
                        Keyword: <input type="text" class="form-control" id="keyword"/>
                        <button class="btn btn-primary" type="button" id="btn_search">
                            <span class="glyphicon glyphicon-search"></span>
                            <span>搜索</span>
                        </button>&nbsp;&nbsp;&nbsp;&nbsp;
                        <button class="btn btn-warning" type="button" id="btn_blacklist">
                            <span class="glyphicon glyphicon-warning-sign"></span>
                            <span>黑名单</span>
                        </button>&nbsp;&nbsp;&nbsp;&nbsp;
                        <button class="btn btn-danger" type="button" id="btn_delete">
                            <span class="glyphicon glyphicon-trash"></span>
                            <span>删除</span>
                        </button>&nbsp;&nbsp;&nbsp;&nbsp;
                    </div>
                    <div class="col-sm-2 col-md-2 col-lg-2 text-right">
                        <select name="page_length" id="page_length" class="form-control">
                            <option value="25">25</option>
                            <option value="50">50</option>
                            <option value="75">75</option>
                            <option value="100">100</option>
                        </select>
                        &nbsp;<label>每页</label>
                    </div>
                    </form>
                </div><hr>

                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12">
                        <table class="table table-striped table-bordered bill_table">
                            <tr>
                                <td>Rendering engine</td>
                                <td>Browser</td>
                                <td>Platform(s)</td>
                                <td>Engine version</td>
                                <td>CSS grade</td>
                            </tr>
                            <tbody>
                                <?php for($i = 0, $len = count($this->data); $i < $len; $i++){ ?>
                                    <tr>
                                        <td><?php echo $this->data[$i][0]; ?></td>
                                        <td><?php echo $this->data[$i][1]; ?></td>
                                        <td><?php echo $this->data[$i][2]; ?></td>
                                        <td><?php echo $this->data[$i][3]; ?></td>
                                        <td><?php echo $this->data[$i][4]; ?></td>
                                    </tr>
                                <?php } ?>

                                <?php if (count($this->data) == 0) { ?>
                                    <tr>
                                        <td colspan="5" class="bill_table_no_data">对不起,没有符合条件的数据</td>
                                    </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- panel footer -->
            <div class="panel-footer">
                <div class="row">
                    <div class="col-sm-6 col-md-6 col-lg-6 text-left">
                    </div>
                    <div class="col-sm-6 col-md-6 col-lg-6 text-right">
                        <ul id="pagination" class="pagination-md"></ul>
                    </div>
                </div>
            </div>
        </div>

        <!-- ------------------------------------------javascript--------------------------------------------------- -->
        <script src="/bootstrap/js/jquery-1.11.0.min.js" charset="UTF-8"></script>
        <script src="/js/jquery.twbsPagination.min.js"></script>
        <script>
        $(document).ready(function(){
            $('#keyword').val('<?php echo $this->keyword; ?>');
            $('#page_length').val(<?php echo $this->page_length; ?>);
        });

        $('#keyword').on('keydown', function(event){
            if (event.keyCode == 13) {
                //enter key
                event.preventDefault();
                $('#btn_search').click();
            }
        });

        $('#btn_search').on('click', function(){
            var keyword = $.trim($('#keyword').val());
            var current_page = <?php echo $this->current_page; ?>;
            var page_length = <?php echo $this->page_length; ?>;
            search(current_page, page_length, keyword);
        });

        /*  --------------------------------------------------------------------------------------------------------  */
        function search(current_page, page_length, keyword)
        {
            var params = {
                'keyword': keyword || $.trim($('#keyword').val()),
                'current_page': current_page || <?php echo $this->current_page; ?>,
                'page_length': page_length || <?php echo $this->page_length; ?>
            };
            location.href = '/demo/index?' + $.param(params);
        }

        $('#pagination').twbsPagination({
            totalPages: <?php echo $this->total_pages; ?>,
            startPage: <?php echo $this->current_page; ?>,
            visiblePages: 7,
            first: '首页',
            prev: '上一页',
            next: '下一页',
            last: '尾页',
            onPageClick: function (event, page) {
                search(page);
            }
        });

        $('#page_length').on('change', function(){
            search(1, this.value);
        });
        </script>
    </body>
</html>